title: OccuSys Workshop @ ACM BuildSys 2026
description: Occupant-Centric Energy Systems (OccuSys) – Modeling and Control Beyond Static Boundaries

url: "https://occusys.github.io"
baseurl: ""   # ← MUST be empty

nav:
  - title: Home
    url: "#home"
  - title: About
    url: "#about"
  - title: Topics
    url: "#topics"
  - title: Dates
    url: "#dates"
  - title: Submission
    url: "#submission"
  - title: Committee
    url: "#organization"
  - title: Contact
    url: "#contact"
