title: OccuSys Workshop @ ACM BuildSys 2026
description: Occupant-Centric Energy Systems (OccuSys) â€“ Modeling and Control Beyond Static Boundaries

baseurl: "/buildsys2026"
url: "https://occusys.github.io"

markdown: kramdown
permalink: pretty

nav:
  - title: Home
    url: "/buildsys2026/#home"
  - title: About
    url: "/buildsys2026/#about"
  - title: Topics
    url: "/buildsys2026/#topics"
  - title: Dates
    url: "/buildsys2026/#dates"
  - title: Submission
    url: "/buildsys2026/#submission"
  - title: Committee
    url: "/buildsys2026/#committee"
  - title: Contact
    url: "/buildsys2026/#contact"



