title: OccuSys Workshop @ ACM BuildSys 2026
description: Occupant-Centric Energy Systems (OccuSys) â€“ Modeling and Control Beyond Static Boundaries

baseurl: "/occusys2026"
url: "https://occusys.github.io"

nav:
  - title: Home
    url: "/occusys2026/#home"
  - title: About
    url: "/occusys2026/#about"
  - title: Topics
    url: "/occusys2026/#topics"
  - title: Dates
    url: "/occusys2026/#dates"
  - title: Submission
    url: "/occusys2026/#submission"
  - title: Committee
    url: "/occusys2026/#committee"
  - title: Contact
    url: "/occusys2026/#contact"
